config/routes.rb
Rails.application.routes.draw do
  get 'home_page/admin'

  get 'home_page/doctor'

  get 'home_page/home'

  get 'home_page/office'

  get 'home_page/patient'

  resources :appointments

  resources :diagnostics

  resources :physicians

  resources :time_slots

  resources :patients

  root 'home_page#home'

end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def admin
  end

  def doctor
  end

  def home
  end

  def office
  end

  def patient
  end
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/views/home_page/admin.html.erb
<body class='ok'>
<h1>System Administrator Page</h1>
<h2>Below are the links to all the background pages for admin adjustment</h2>
<li><%= button_to "Patient", patients_path, :method => :get %></li> |
<li><%= button_to "Physician", physicians_path, :method => :get %></li> |
<li><%= button_to "Time Slots", time_slots_path, :method => :get %></li> |
<li><%= button_to "Diagnostic Codes", diagnostics_path, :method => :get %></li>
<p></p>
</body>

app/views/home_page/doctor.html.erb
<body class='ok'>
<h1>Doctor's Homepage</h1>
<li><%= button_to "Home", home_page_home_path, :method => :get %></li> |
<li><%= button_to "Patients", patients_path, :method => :get %></li> |
<li><%= button_to "Patient Appointment", appointments_path, :method => :get %></li>
<p></p>
</body>

app/views/home_page/home.html.erb
<h1 class="homep">Welcome to Dermatologists Associates Homepage!</h1>

<body class='ok'>

<p></p>
<br>
<br>


<ul>
<li>
<%= button_to 'Patient', home_page_patient_path, :class => 'button', :method => :get %>
</li>

<li>
  <%= button_to 'Physician', home_page_doctor_path, :class => 'button', :method => :get %>
</li>

<li>
  <%= button_to 'Sys Admin', home_page_admin_path, :class => 'button', :method => :get %>
</li>

<li>
  <%= button_to 'Office', home_page_office_path, :class => 'button', :method => :get %>
</li>
</ul>


</body>

app/views/home_page/office.html.erb
<body class='ok'>

<h1>Welcome Office Workers</h1>
<p>Please go to the patients page and click on show for the patient you want an invoice for.</p>

<%= button_to 'Patient Payment Invoice', patients_path, :method => :get %>
</body>

app/views/home_page/patient.html.erb
<body class='ok'>
<h1>Welcome to the Patient Portal!</h1>
<li><%= button_to "Appointments", new_appointment_path, :method => :get %></li> |
<li><%= button_to "New Patient Signup", new_patient_path, :method => :get %></li>
<li><%= button_to "Edit your Appointment", patients_path, :method => :get %></li>
<p></p>
</body>