config/routes.rb
Rails.application.routes.draw do
  get 'home_page/admin'

  get 'home_page/doctor'

  get 'home_page/home'

  get 'home_page/office'

  get 'home_page/patient'

  resources :appointments

  resources :diagnostics

  resources :physicians

  resources :time_slots

  resources :patients

  root 'home_page#home'

end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  has_many :appointments

  validates :time_string, :time_num, presence: true
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  before_action :set_time_slot, only: [:show, :edit, :update, :destroy]

  # GET /time_slots
  # GET /time_slots.json
  def index
    @time_slots = TimeSlot.all
  end

  # GET /time_slots/1
  # GET /time_slots/1.json
  def show
  end

  # GET /time_slots/new
  def new
    @time_slot = TimeSlot.new
  end

  # GET /time_slots/1/edit
  def edit
  end

  # POST /time_slots
  # POST /time_slots.json
  def create
    @time_slot = TimeSlot.new(time_slot_params)

    respond_to do |format|
      if @time_slot.save
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully created.' }
        format.json { render :show, status: :created, location: @time_slot }
      else
        format.html { render :new }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_slots/1
  # PATCH/PUT /time_slots/1.json
  def update
    respond_to do |format|
      if @time_slot.update(time_slot_params)
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_slot }
      else
        format.html { render :edit }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slots/1
  # DELETE /time_slots/1.json
  def destroy
    @time_slot.destroy
    respond_to do |format|
      format.html { redirect_to time_slots_url, notice: 'Time slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_slot
      @time_slot = TimeSlot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_slot_params
      params.require(:time_slot).permit(:time_string, :time_num, :time_availability)
    end
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/time_slots/_form.html.erb
<%= form_for(@time_slot) do |f| %>
  <% if @time_slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_slot.errors.count, "error") %> prohibited this time_slot from being saved:</h2>

      <ul>
      <% @time_slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <b><%= f.label :time_string %></b><br>
    <%= f.text_field :time_string %>
  </div>
  <div class="field">
    <b><%= f.label :time_num %></b><br>
    <%= f.time_select :time_num, {ampm: true} %>
  </div>
  <div class="field">
    <b><%= f.label :time_availability %></b><br>
    <%= f.check_box :time_availability %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_slots/edit.html.erb
<h1>Time Slot Editor</h1>

<%= render 'form' %>

<li><%= button_to 'Show Time Slot', @time_slot, :method => :get %></li> |
<li><%= button_to 'Back to Time Slot List', time_slots_path, :method => :get %></li>

app/views/time_slots/index.html.erb
<h1>Time Slot List</h1>

<table>
  <thead>
    <tr>
      <th>Time string</th>
      <th>Time num</th>
      <th>Time availability</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @time_slots.each do |time_slot| %>
      <tr>
        <td><%= time_slot.time_string %></td>
        <td><%= time_slot.time_num %></td>
        <td><%= time_slot.time_availability %></td>
        <td><%= link_to 'Show', time_slot %></td>
        <td><%= link_to 'Edit', edit_time_slot_path(time_slot) %></td>
        <td><%= link_to 'Destroy', time_slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Time slot', new_time_slot_path,:method => :get %>

app/views/time_slots/new.html.erb
<h1>New Time Slot</h1>

<%= render 'form' %>

<%= button_to 'Back to Time Slot List', time_slots_path, :method => :get %>

app/views/time_slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time string:</strong>
  <%= @time_slot.time_string %>
</p>

<p>
  <strong>Time num:</strong>
  <%= @time_slot.time_num %>
</p>

<p>
  <strong>Time availability:</strong>
  <%= @time_slot.time_availability %>
</p>

<li><%= button_to 'Edit Time Slot', edit_time_slot_path(@time_slot), :method => :get %></li> |
<li><%= button_to 'Back to Time Slot List', time_slots_path, :method => :get %></li>