config/routes.rb
Rails.application.routes.draw do
  get 'home_page/admin'

  get 'home_page/doctor'

  get 'home_page/home'

  get 'home_page/office'

  get 'home_page/patient'

  resources :appointments

  resources :diagnostics

  resources :physicians

  resources :time_slots

  resources :patients

  root 'home_page#home'

end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :patients, through: :appointments
  has_many :diagnostics, through: :appointments
  has_many :time_slots, through:  :appointments

  validates :physician_name, :physician_address, :physician_city, :physician_zip, :physician_primary_phone, presence: true

  def if_true
    if self.physician_status == 'true'
      self.physician_status = 'Available'
    end
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]

  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, notice: 'Physician was successfully created.' }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1
  # PATCH/PUT /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to @physician, notice: 'Physician was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician.destroy
    respond_to do |format|
      format.html { redirect_to physicians_url, notice: 'Physician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physician_params
      params.require(:physician).permit(:physician_name, :physician_address, :physician_city, :physician_zip, :physician_primary_phone, :physician_secondary_phone, :physician_status)
    end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_form.html.erb
<%= form_for(@physician) do |f| %>
  <% if @physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% @physician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <b><%= f.label :physician_name %></b><br>
    <%= f.text_field :physician_name %>
  </div>
  <div class="field">
   <b><%= f.label :physician_address %></b><br>
    <%= f.text_field :physician_address %>
  </div>
  <div class="field">
   <b><%= f.label :physician_city %></b><br>
    <%= f.text_field :physician_city %>
  </div>
  <div class="field">
    <b><%= f.label :physician_zip %></b><br>
    <%= f.text_field :physician_zip %>
  </div>
  <div class="field">
   <b><%= f.label :physician_primary_phone %></b><br>
    <%= f.text_field :physician_primary_phone %>
  </div>
  <div class="field">
    <b><%= f.label :physician_secondary_phone %></b><br>
    <%= f.text_field :physician_secondary_phone %>
  </div>
  <div class="field">
   <b><%= f.label :physician_status %></b><br>
    <%= f.check_box :physician_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physicians/edit.html.erb
<h1>Editing Dr. <%= @physician.physician_name %></h1>

<%= render 'form' %>

<li><%= button_to 'Show', @physician, :method => :get %></li> |
<li><%= button_to 'Back', physicians_path, :method => :get %></li>

app/views/physicians/index.html.erb
<h1>Physicians List</h1>

<table>
  <thead>
    <tr>
      <th>Physician name</th>
      <th>Physician address</th>
      <th>Physician city</th>
      <th>Physician zip</th>
      <th>Physician primary phone</th>
      <th>Physician secondary phone</th>
      <th>Physician status</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @physicians.order(:physician_name).each do |physician| %>
      <tr>
        <td><%= physician.physician_name %></td>
        <td><%= physician.physician_address %></td>
        <td><%= physician.physician_city %></td>
        <td><%= physician.physician_zip %></td>
        <td><%= physician.physician_primary_phone %></td>
        <td><%= physician.physician_secondary_phone %></td>
        <td><%= physician.physician_status %></td>
        <td><%= link_to 'Show', physician %></td>
        <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
        <td><%= link_to 'Destroy', physician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Physician', new_physician_path, :method => :get %>

app/views/physicians/new.html.erb
<h1>New Physician Entry</h1>

<%= render 'form' %>

<%= button_to 'Back to Physicians List', physicians_path, :method => :get %>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>


<h1>The appointments for <%= @physician.physician_name %> are:</h1>

<p>
  <strong>Physician name:</strong>
  <%= @physician.physician_name %>
</p>

<p>
  <strong>Physician address:</strong>
  <%= @physician.physician_address %>
</p>

<p>
  <strong>Physician city:</strong>
  <%= @physician.physician_city %>
</p>

<p>
  <strong>Physician zip:</strong>
  <%= @physician.physician_zip %>
</p>

<p>
  <strong>Physician primary phone:</strong>
  <%= @physician.physician_primary_phone %>
</p>

<p>
  <strong>Physician secondary phone:</strong>
  <%= @physician.physician_secondary_phone %>
</p>

<p>
  <strong>Physician status:</strong>
  <%= @physician.physician_status %>
</p>

<table>
  <thead>
  <tr>
    <th>Appointment Date</th>
    <th>Patient ID</th>
    <th>Patient Name</th>
    <th>Patient Diagnostic</th>
    <th>Diagnostic Cost</th>
    <th>Invoiced Appointment Amount</th>
    <th colspan ="3"></th>
  </tr>
  </thead>

<tbody>
<% @physician.appointments.each do |appointment| %>
    <tr>
      <td><%= appointment.appointment_date %></td>
      <td><%= appointment.patient_id %></td>
      <td><%= appointment.patient.patient_name %></td>
      <td><%= appointment.diagnostic.diagnostic_desc %></td>
      <td><%= number_to_currency(appointment.diagnostic.cost) %> </td>
      <td><%= number_to_currency(appointment.diagnostic.cost) %> </td>
    </tr>
<% end %>
</tbody>

</table>
<br>

<li><%= button_to 'Edit Physician', edit_physician_path(@physician), :method => :get %></li> |
<li><%= button_to 'Back to Physician Listing', physicians_path, :method => :get %></li>