config/routes.rb
Rails.application.routes.draw do
  get 'home_page/admin'

  get 'home_page/doctor'

  get 'home_page/home'

  get 'home_page/office'

  get 'home_page/patient'

  resources :appointments

  resources :diagnostics

  resources :physicians

  resources :time_slots

  resources :patients

  root 'home_page#home'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, through: :appointments
  has_many :diagnostics, through: :appointments
  has_many :time_slots, through:  :appointments

  validates :patient_name, presence: true
  validates :patient_address, :patient_city, :patient_zip, :patient_primary_phone,  presence: true


end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:patient_name, :patient_address, :patient_city, :patient_zip, :patient_primary_phone, :patient_secondary_phone)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <b><%= f.label :patient_name %></b><br>
    <%= f.text_field :patient_name %>
  </div>
  <div class="field">
   <b><%= f.label :patient_address %></b><br>
    <%= f.text_field :patient_address %>
  </div>
  <div class="field">
    <b><%= f.label :patient_city %></b><br>
    <%= f.text_field :patient_city %>
  </div>
  <div class="field">
   <b><%= f.label :patient_zip %></b><br>
    <%= f.text_field :patient_zip %>
  </div>
  <div class="field">
    <b><%= f.label :patient_primary_phone %></b><br>
    <%= f.text_field :patient_primary_phone %>
  </div>
  <div class="field">
    <b><%= f.label :patient_secondary_phone %></b><br>
    <%= f.text_field :patient_secondary_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing <%= @patient.patient_name %></h1>

<%= render 'form' %>

<li><%= button_to 'Show', @patient, :method => :get %></li> |
<li><%= button_to 'Back to Patients Page', patients_path, :method => :get %></li>

app/views/patients/index.html.erb
<h1>Patient Listing</h1>

<table>
  <thead>
    <tr>
      <th>Patient name</th>
      <th>Patient address</th>
      <th>Patient city</th>
      <th>Patient zip</th>
      <th>Patient primary phone</th>
      <th>Patient secondary phone</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @patients.order(:patient_name).each do |patient| %>
      <tr>
        <td><%= patient.patient_name %></td>
        <td><%= patient.patient_address %></td>
        <td><%= patient.patient_city %></td>
        <td><%= patient.patient_zip %></td>
        <td><%= patient.patient_primary_phone %></td>
        <td><%= patient.patient_secondary_phone %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Patient', new_patient_path, :method => :get %>

app/views/patients/new.html.erb
<h1>New Patient Entry</h1>

<%= render 'form' %>

<%= button_to 'Back to Patient List', patients_path, :method => :get %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @patient.patient_name %>'s Completed Appointments</h2>
<p>
  <strong>Patient name:</strong>
  <%= @patient.patient_name %>
</p>

<p>
  <strong>Patient address:</strong>
  <%= @patient.patient_address %>
</p>

<p>
  <strong>Patient city:</strong>
  <%= @patient.patient_city %>
</p>

<p>
  <strong>Patient zip:</strong>
  <%= @patient.patient_zip %>
</p>

<p>
  <strong>Patient primary phone:</strong>
  <%= @patient.patient_primary_phone %>
</p>

<p>
  <strong>Patient secondary phone:</strong>
  <%= @patient.patient_secondary_phone %>
</p>

<table>
  <thead>
  <tr>
    <th>Appointment Date</th>
    <th>Patient ID</th>
    <th>Patient Name</th>
    <th>Patient Diagnostic</th>
    <th>Diagnostic Cost</th>
    <th>Final Appointment Cost</th>
    <th colspan ="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @patient.appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.appointment_date %></td>
        <td><%= appointment.patient_id %></td>
        <td><%= appointment.patient.patient_name %></td>
        <td><%= appointment.diagnostic.diagnostic_desc %></td>
        <td><%= number_to_currency(appointment.diagnostic.cost) %> </td>
        <td><%= number_to_currency(appointment.diagnostic.cost) %> </td>
      </tr>
  <% end %>
  </tbody>

</table>
<br>

<tbody>

    <tr>
      <td><b>The Year to Date Sum is: </b></td>
      <td><b><%= number_to_currency(@patient.diagnostics.sum(:cost)) %></b></td>
    </tr>
    <p>
    <tr>
      <td><b>What you owe today is: </b></td>
      <td><% @patient.appointments.where({appointment_date: Date.today}).each do |appointment| %></td>
      <td><b><%= (appointment.diagnostic.cost) %></b></td>
    </tr>
          <% end %>
    </p>
</tbody>
</table>
<br>




<li><%= button_to 'Edit', edit_patient_path(@patient), :method => :get %></li> |
<li><%= button_to 'Edit Patient Appointment', edit_appointment_path(@patient), :method => :get %></li> |
<li><%= button_to 'Back', patients_path, :method => :get %></li>